### ISSUE TITLE
Error 500 when I push a package

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-gkeeper#426]
I found the following error in the gtk-api:
You can reproduce it running the integration test **int-1-gtkpkg-sp-catalogue**

```
06:57:33 web.1 | 2017-02-21 06:57:33 - NoMethodError - undefined method `url' for PackageManagerService:Class:
06:57:33 web.1 | /app/routes/package.rb:46:in `block (2 levels) in <class:GtkApi>'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
06:57:33 web.1 | /usr/local/bundle/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
06:57:33 web.1 | /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/rack-1.6.5/lib/rack/logger.rb:15:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/puma-3.6.2/lib/puma/configuration.rb:225:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
06:57:33 web.1 | /usr/local/bundle/gems/puma-3.6.2/lib/puma/thread_pool.rb:116:in `call'
06:57:33 web.1 | /usr/local/bundle/gems/puma-3.6.2/lib/puma/server.rb:275:in `block in run'
06:57:33 web.1 | /usr/local/bundle/gems/puma-3.6.2/lib/puma/server.rb:415:in `process_client'
06:57:33 web.1 | /usr/local/bundle/gems/puma-3.6.2/lib/puma/server.rb:578:in `handle_request'
06:57:33 web.1 | 10.30.0.110 - - [21/Feb/2017:06:57:33 +0000] "POST /api/v2/packages HTTP/1.1" 500 30 1.4896

```

**Comment by jbonnet** [comment]
int-1-gtkpkg-sp-catalogue running green again, Sir!

;-)
