### ISSUE TITLE
Fix package validation bug

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#702]
Integration with the Package Validation module (`son-validate`) has a bug:
```
E, [2017-06-12T08:37:57.791166 #6] ERROR -- GtkApi::Validator#valid_package?: Error during processing: no implicit conversion of Tempfile into String
E, [2017-06-12T08:37:57.791279 #6] ERROR -- GtkApi::Validator#valid_package?: Backtrace:
	/app/models/validator.rb:62:in `http_post'
	/app/models/validator.rb:62:in `valid_package?'
```

**Comment by jbonnet** [comment]
Closed by PR #731
