### ISSUE TITLE
Fix undefined method call

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#821]
```
...
D, [2017-08-18T14:46:30.641556 #6] DEBUG -- GtkApi::ManagerService#postCurb: response body={"error":"Token not active"}
E, [2017-08-18T14:46:30.641651 #6] ERROR -- GtkApi::ManagerService#postCurb: Status 401
D, [2017-08-18T14:46:30.641699 #6] DEBUG -- GtkApi::User#find_username_by_token: response= {:status=>401, :count=>nil, :items=>nil, :message=>"Status 401: could not process"}
E, [2017-08-18T14:46:30.641842 #6] ERROR -- GtkApi::User#find_username_by_token: Status 401: token not active
2017-08-18 14:46:30 - NoMethodError - undefined method `call' for :kpi_method:Symbol:
	/app/helpers/common.rb:97:in `rescue in get_username_by_token'
	/app/helpers/common.rb:94:in `get_username_by_token'
	/app/routes/request.rb:63:in `block (2 levels) in <class:GtkApi>'
...
```

**Comment by jbonnet** [comment]
Closed by PR #920
